apiVersion: v1
kind: Service
metadata:
   name: event-service
   labels:
     name: event-service
     app: event-app
spec:
  type: NodePort
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30008
  selector:
    name: events-pod
    app: event-app
    
