apiVersion: v1
kind: Service
metadata:
  name: my-keykloak-service
  labels:
    name: my-keykloak-service
    app: my-keykloak-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: keykloak-deployment


