apiVersion: v1
kind: Service
metadata:
   name: mongodb
   labels:
     name: mongo-service
     app: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30003
  selector:
    name: mongodb
    app: mongodb
