apiVersion: v1
kind: Service
metadata:
  name: registration-service
  labels:
    name: registration-service
    app: registration-app
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort:
  selector:
    name: registration
    app: registration-app
